import Foundation

// Curated level set — generated by scripts/gen_levels.py (ported solver/generator
// from legacy-expo/src/engine), verified so every level's solutionCount matches
// a fresh solver run. Regenerate by editing tier specs and rerunning the script.

enum Levels {
    static let all: [LevelDef] = [
        LevelDef(
            id: "L01-tutorial-add",
            values: [3, 6, 2],
            operators: [.add, .add],
            target: 11,
            solutionCount: 2,
            totalArrangements: 2
        ),
        LevelDef(
            id: "L02-tutorial-add",
            values: [1, 6, 9],
            operators: [.add, .add],
            target: 16,
            solutionCount: 2,
            totalArrangements: 2
        ),
        LevelDef(
            id: "L03-tutorial-add",
            values: [2, 5, 9],
            operators: [.add, .add],
            target: 16,
            solutionCount: 2,
            totalArrangements: 2
        ),
        LevelDef(
            id: "L04-tutorial-add",
            values: [8, 7, 4],
            operators: [.add, .add],
            target: 19,
            solutionCount: 2,
            totalArrangements: 2
        ),
        LevelDef(
            id: "L05-intro-mixed",
            values: [4, 2, 1],
            operators: [.multiply, .add],
            target: 12,
            solutionCount: 1,
            totalArrangements: 2
        ),
        LevelDef(
            id: "L06-intro-mixed",
            values: [3, 3, 4],
            operators: [.add, .multiply],
            target: 24,
            solutionCount: 1,
            totalArrangements: 2
        ),
        LevelDef(
            id: "L07-intro-mixed",
            values: [4, 4, 6],
            operators: [.add, .multiply],
            target: 28,
            solutionCount: 1,
            totalArrangements: 2
        ),
        LevelDef(
            id: "L08-intro-mixed",
            values: [4, 3, 3],
            operators: [.add, .multiply],
            target: 13,
            solutionCount: 1,
            totalArrangements: 2
        ),
        LevelDef(
            id: "L09-intro-mixed",
            values: [4, 6, 5],
            operators: [.add, .multiply],
            target: 50,
            solutionCount: 1,
            totalArrangements: 2
        ),
        LevelDef(
            id: "L10-intro-mixed",
            values: [5, 6, 3],
            operators: [.multiply, .add],
            target: 33,
            solutionCount: 1,
            totalArrangements: 2
        ),
        LevelDef(
            id: "L11-intro-mixed",
            values: [2, 5, 2],
            operators: [.add, .multiply],
            target: 12,
            solutionCount: 1,
            totalArrangements: 2
        ),
        LevelDef(
            id: "L12-intro-mixed",
            values: [1, 3, 5],
            operators: [.add, .multiply],
            target: 16,
            solutionCount: 1,
            totalArrangements: 2
        ),
        LevelDef(
            id: "L13-core-4",
            values: [5, 1, 3, 5],
            operators: [.multiply, .add, .add],
            target: 25,
            solutionCount: 1,
            totalArrangements: 5
        ),
        LevelDef(
            id: "L14-core-4",
            values: [5, 5, 1, 3],
            operators: [.multiply, .add, .multiply],
            target: 40,
            solutionCount: 1,
            totalArrangements: 5
        ),
        LevelDef(
            id: "L15-core-4",
            values: [6, 5, 6, 3],
            operators: [.multiply, .add, .add],
            target: 69,
            solutionCount: 1,
            totalArrangements: 5
        ),
        LevelDef(
            id: "L16-core-4",
            values: [1, 3, 1, 6],
            operators: [.add, .multiply, .add],
            target: 28,
            solutionCount: 1,
            totalArrangements: 5
        ),
        LevelDef(
            id: "L17-core-4",
            values: [2, 6, 6, 6],
            operators: [.multiply, .add, .add],
            target: 30,
            solutionCount: 1,
            totalArrangements: 5
        ),
        LevelDef(
            id: "L18-core-4",
            values: [3, 3, 5, 4],
            operators: [.add, .multiply, .multiply],
            target: 72,
            solutionCount: 1,
            totalArrangements: 5
        ),
        LevelDef(
            id: "L19-core-4",
            values: [2, 3, 2, 6],
            operators: [.multiply, .add, .add],
            target: 16,
            solutionCount: 1,
            totalArrangements: 5
        ),
        LevelDef(
            id: "L20-core-4",
            values: [1, 2, 5, 2],
            operators: [.add, .multiply, .multiply],
            target: 22,
            solutionCount: 1,
            totalArrangements: 5
        ),
        LevelDef(
            id: "L21-core-4",
            values: [5, 6, 1, 3],
            operators: [.add, .add, .multiply],
            target: 26,
            solutionCount: 1,
            totalArrangements: 5
        ),
        LevelDef(
            id: "L22-core-4",
            values: [1, 2, 1, 5],
            operators: [.add, .add, .multiply],
            target: 16,
            solutionCount: 1,
            totalArrangements: 5
        ),
        LevelDef(
            id: "L23-core-5",
            values: [4, 2, 5, 3, 2],
            operators: [.multiply, .multiply, .add, .add],
            target: 54,
            solutionCount: 1,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L24-core-5",
            values: [2, 5, 3, 5, 5],
            operators: [.multiply, .add, .add, .multiply],
            target: 38,
            solutionCount: 2,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L25-core-5",
            values: [3, 3, 1, 3, 1],
            operators: [.multiply, .add, .add, .add],
            target: 16,
            solutionCount: 2,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L26-core-5",
            values: [2, 4, 2, 5, 5],
            operators: [.multiply, .add, .multiply, .multiply],
            target: 140,
            solutionCount: 2,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L27-core-5",
            values: [1, 1, 5, 1, 3],
            operators: [.add, .multiply, .multiply, .add],
            target: 21,
            solutionCount: 2,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L28-core-5",
            values: [2, 2, 5, 5, 4],
            operators: [.add, .add, .multiply, .multiply],
            target: 142,
            solutionCount: 2,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L29-core-5",
            values: [2, 2, 3, 2, 1],
            operators: [.add, .multiply, .add, .add],
            target: 24,
            solutionCount: 2,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L30-core-5",
            values: [3, 4, 3, 3, 4],
            operators: [.add, .add, .multiply, .multiply],
            target: 55,
            solutionCount: 1,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L31-core-5",
            values: [3, 4, 3, 2, 3],
            operators: [.multiply, .multiply, .add, .add],
            target: 63,
            solutionCount: 2,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L32-core-5",
            values: [4, 3, 5, 4, 3],
            operators: [.add, .add, .add, .multiply],
            target: 40,
            solutionCount: 2,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L33-advanced-5",
            values: [5, 4, 6, 2, 2],
            operators: [.add, .multiply, .add, .add],
            target: 74,
            solutionCount: 1,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L34-advanced-5",
            values: [5, 1, 2, 3, 5],
            operators: [.multiply, .add, .add, .multiply],
            target: 130,
            solutionCount: 1,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L35-advanced-5",
            values: [4, 3, 5, 4, 3],
            operators: [.multiply, .multiply, .add, .add],
            target: 120,
            solutionCount: 1,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L36-advanced-5",
            values: [6, 2, 5, 4, 2],
            operators: [.add, .multiply, .multiply, .add],
            target: 176,
            solutionCount: 1,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L37-advanced-5",
            values: [3, 3, 1, 4, 5],
            operators: [.multiply, .add, .multiply, .add],
            target: 90,
            solutionCount: 1,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L38-advanced-5",
            values: [3, 1, 3, 2, 6],
            operators: [.add, .add, .multiply, .add],
            target: 35,
            solutionCount: 1,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L39-advanced-5",
            values: [1, 2, 6, 3, 3],
            operators: [.add, .add, .multiply, .multiply],
            target: 61,
            solutionCount: 1,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L40-advanced-5",
            values: [2, 2, 1, 5, 6],
            operators: [.add, .multiply, .add, .multiply],
            target: 44,
            solutionCount: 1,
            totalArrangements: 14
        ),
        LevelDef(
            id: "L41-capstone-6",
            values: [5, 5, 1, 5, 1, 2],
            operators: [.add, .add, .multiply, .add, .multiply],
            target: 67,
            solutionCount: 1,
            totalArrangements: 42
        ),
        LevelDef(
            id: "L42-capstone-6",
            values: [4, 3, 3, 4, 2, 4],
            operators: [.multiply, .add, .multiply, .add, .add],
            target: 160,
            solutionCount: 1,
            totalArrangements: 42
        ),
        LevelDef(
            id: "L43-capstone-6",
            values: [3, 3, 2, 4, 5, 4],
            operators: [.add, .add, .add, .multiply, .multiply],
            target: 135,
            solutionCount: 1,
            totalArrangements: 42
        ),
        LevelDef(
            id: "L44-capstone-6",
            values: [3, 2, 4, 3, 5, 3],
            operators: [.multiply, .add, .multiply, .multiply, .add],
            target: 144,
            solutionCount: 1,
            totalArrangements: 42
        ),
        LevelDef(
            id: "L45-capstone-6",
            values: [3, 4, 2, 4, 1, 1],
            operators: [.multiply, .add, .multiply, .multiply, .add],
            target: 40,
            solutionCount: 1,
            totalArrangements: 42
        ),
        LevelDef(
            id: "L46-capstone-6",
            values: [4, 5, 2, 2, 5, 5],
            operators: [.multiply, .multiply, .add, .add, .add],
            target: 105,
            solutionCount: 1,
            totalArrangements: 42
        ),
        LevelDef(
            id: "L47-capstone-6",
            values: [3, 2, 4, 1, 3, 5],
            operators: [.add, .multiply, .add, .add, .multiply],
            target: 68,
            solutionCount: 1,
            totalArrangements: 42
        ),
        LevelDef(
            id: "L48-capstone-6",
            values: [5, 3, 3, 2, 2, 2],
            operators: [.multiply, .multiply, .add, .multiply, .add],
            target: 85,
            solutionCount: 1,
            totalArrangements: 42
        ),
        LevelDef(
            id: "L49-master-7",
            values: [3, 2, 1, 3, 4, 1, 2],
            operators: [.add, .add, .add, .multiply, .add, .multiply],
            target: 47,
            solutionCount: 1,
            totalArrangements: 132
        ),
        LevelDef(
            id: "L50-master-7",
            values: [3, 1, 4, 2, 1, 3, 3],
            operators: [.add, .add, .add, .multiply, .add, .multiply],
            target: 78,
            solutionCount: 1,
            totalArrangements: 132
        ),
        LevelDef(
            id: "L51-master-7",
            values: [3, 4, 1, 4, 1, 2, 3],
            operators: [.add, .multiply, .add, .add, .multiply, .multiply],
            target: 111,
            solutionCount: 1,
            totalArrangements: 132
        ),
        LevelDef(
            id: "L52-master-7",
            values: [2, 1, 1, 2, 2, 1, 4],
            operators: [.add, .add, .multiply, .multiply, .multiply, .add],
            target: 40,
            solutionCount: 1,
            totalArrangements: 132
        ),
        LevelDef(
            id: "L53-master-7",
            values: [3, 1, 2, 3, 3, 2, 1],
            operators: [.multiply, .add, .add, .multiply, .multiply, .add],
            target: 30,
            solutionCount: 1,
            totalArrangements: 132
        ),
        LevelDef(
            id: "L54-master-7",
            values: [2, 2, 4, 3, 2, 3, 2],
            operators: [.add, .multiply, .add, .add, .add, .multiply],
            target: 38,
            solutionCount: 1,
            totalArrangements: 132
        ),
    ]
}
